# -*- coding: utf-8 -*-
"""dizionario_terzine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqZQsnLOOiyMiaIcjhMixLptI_KPkvtu
"""

#!pip install lxml

from lxml import etree
import pandas as pd

#from google.colab import drive
#drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Colab_Notebooks/Commedia_Petrocchi_XML_TEI.xml'

parser = etree.XMLParser(recover=True)
xml_data = etree.parse(file_path, parser)

cantica = xml_data.xpath('//div1/@id')[0]
tot_canti = xml_data.xpath('//div1[@id="Inferno"]//div2')

cantiche = xml_data.xpath('//div1')
canti = {}


for cantica_element in cantiche:
    cantica = cantica_element.xpath('./@id')[0]
    tot_canti = cantica_element.xpath('./div2')


    for c in tot_canti:
        h_canto = c.xpath('.//head//text()')
        terzine = []
        terzina = ["".join(l.itertext()).strip() for l in c.xpath('.//l') if "".join(l.itertext()).strip()]

        for i in range(0, len(terzina), 3):
            terzine.append(terzina[i:i+3])

        canti[(cantica, h_canto[0])] = terzine


data = []
for (cantica, titolo), ter in canti.items():
    i = 1
    for t in ter:
        if len(t) == 3:
            range_versi = f"{i}-{i+2}"
            frase = " ".join(t)
            data.append([cantica, titolo, range_versi, frase])
            i += 3
        else:
            for verso in t:
                range_versi = f"{i}"
                data.append([cantica, titolo, range_versi, verso])
                i += 1


df = pd.DataFrame(data, columns=['cantica', 'canto', 'range_versi', 'terzina'])
df['range_versi'] = "\u200B" + df['range_versi'].astype(str)
df.to_csv("terzine.csv", index=False, sep=';', encoding='utf-8-sig')
print(df)

